set(_CATKIN_CURRENT_PACKAGE "fl_description")
set(fl_description_VERSION "0.0.0")
set(fl_description_MAINTAINER "marat <amx1989@yandex.ru>")
set(fl_description_PACKAGE_FORMAT "2")
set(fl_description_BUILD_DEPENDS )
set(fl_description_BUILD_EXPORT_DEPENDS )
set(fl_description_BUILDTOOL_DEPENDS "catkin")
set(fl_description_BUILDTOOL_EXPORT_DEPENDS )
set(fl_description_EXEC_DEPENDS )
set(fl_description_RUN_DEPENDS )
set(fl_description_TEST_DEPENDS )
set(fl_description_DOC_DEPENDS )
set(fl_description_URL_WEBSITE "")
set(fl_description_URL_BUGTRACKER "")
set(fl_description_URL_REPOSITORY "")
set(fl_description_DEPRECATED "")