set(_CATKIN_CURRENT_PACKAGE "fl_gazebo")
set(fl_gazebo_VERSION "0.0.0")
set(fl_gazebo_MAINTAINER "marat <amx1989@yandex.ru>")
set(fl_gazebo_PACKAGE_FORMAT "2")
set(fl_gazebo_BUILD_DEPENDS )
set(fl_gazebo_BUILD_EXPORT_DEPENDS )
set(fl_gazebo_BUILDTOOL_DEPENDS "catkin")
set(fl_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(fl_gazebo_EXEC_DEPENDS )
set(fl_gazebo_RUN_DEPENDS )
set(fl_gazebo_TEST_DEPENDS )
set(fl_gazebo_DOC_DEPENDS )
set(fl_gazebo_URL_WEBSITE "")
set(fl_gazebo_URL_BUGTRACKER "")
set(fl_gazebo_URL_REPOSITORY "")
set(fl_gazebo_DEPRECATED "")