set(_CATKIN_CURRENT_PACKAGE "fl_hardware")
set(fl_hardware_VERSION "0.0.0")
set(fl_hardware_MAINTAINER "marat <amx1989@yandex.ru>")
set(fl_hardware_PACKAGE_FORMAT "2")
set(fl_hardware_BUILD_DEPENDS )
set(fl_hardware_BUILD_EXPORT_DEPENDS )
set(fl_hardware_BUILDTOOL_DEPENDS "catkin")
set(fl_hardware_BUILDTOOL_EXPORT_DEPENDS )
set(fl_hardware_EXEC_DEPENDS )
set(fl_hardware_RUN_DEPENDS )
set(fl_hardware_TEST_DEPENDS )
set(fl_hardware_DOC_DEPENDS )
set(fl_hardware_URL_WEBSITE "")
set(fl_hardware_URL_BUGTRACKER "")
set(fl_hardware_URL_REPOSITORY "")
set(fl_hardware_DEPRECATED "")